### ISSUE TITLE
NPath complexity are increased after "else" branch was removed and "return" statement was added

### ISSUE THREAD

**Issue by EvgenyUnvsoft** [phpmd/phpmd#282]
First example

```
function Test($a, $b)
{
    if ($a > $b) {
        $result = $a;
    } else {
        if ($a > 5) {
            $result = 6;
        } else {
            $result = 4
        }
    }

    return $result;
}
```

For this function PHPMD return NPath complexity 3.

Make some changes - remove "else" branches and add return statement to the if branches.

```
function Test($a, $b)
{
    if ($a > $b) {
        $result = $a;

        return $result;
    }

    if ($a > 5) {
        $result = 6;

        return $result;
    }

    $result = 4

    return $result;
}
```

For this function PHPMD return NPath complexity 4.

Why NPath complexity increased?

**Comment by offsides** [comment]
That is actually (technically) correct.  The first function has 3 possible paths:  The first if gives one path if it's true, or two paths if it's false (inside the else).  The second function has 4 possible paths (2 for each if) because the return is not accounted for by the NPath calculation (return has the same effect as a goto - it sends you elsewhere, and thus is not really calculable).

The issue isn't with the implementation (as opposed to the improper calculation for the ternary operator - see https://github.com/pdepend/pdepend/issues/261), but the actual NPath spec.  You are correct that the true case for the first if should never see the second if statement, but as far as I can see from reading the original NPath article there is no accounting for that fact (perhaps because if the return fails, it will fall through and continue?).  If you want to remove the nested if within the else, just change the second if to an elseif (since it should never be evaluated if the first if is true) and your NPath complexity should drop back down.

**Comment by EvgenyUnvsoft** [comment]
Thanks for your explanation

**Comment by ossinkine** [comment]
Actually this is a bug and I suggest to reopen the issue. @offsides I don't know which original NPath article do you talking about but as I understand NPath complexity is in how many ways the interpreter can execute the program depending on the input data. So the NPath complexity of both above examples is 3. It's the same with the other manual. The same goes for throwing exception, not just return statement.

**Comment by offsides** [comment]
The original NPath specification comes from an article in the Communications of the ACM, which is now available online here: https://www.thefreelibrary.com/NPATH%3A+a+measure+of+execution+path+complexity+and+its+applications.-a06242192

You are incorrect that the NPath of both examples above is 3.  In the first one, it is 3 - 1 for if the first if is true, and then if it's false (second path) that has 2 possible paths for the nested if giving a total NPath of 3.  The second has 4 paths - 2 for the first if (one if true, one if false even though there's no else) and 2 for the second if (same reasoning).  The reason for this is that NPath is limited in that it's NOT about how many paths through the code you might actually take based on input data, but how many POSSIBLE paths there are through the code regardless of input data.  A return statement doesn't change the fact that there are 2 possible paths even if it guarantees that later paths can never be taken once it's executed.

That's why I said it's an issue with the NPath spec - it doesn't take into account the fact that some cases just can't happen, partially because that's more of a subjective interpretation rather than an objective one (return is pretty straightforward, but goto makes a mess of everything and there's no telling what may or may not happen within a function call that might prevent later branches from being executed, etc.).  Then again, something like this can also help you tighten up your code a little, which is probably the whole point of the NPath metric in the first place.

**Comment by kylekatarnls** [comment]
Thanks @offsides for this great explanation. I guess we can't have an exact representation of the cyclomatic complexity.
