### ISSUE TITLE
document has some mistake

### ISSUE THREAD

**Issue by twinszhao1983** [phpmd/phpmd#315]
http://phpmd.org/support/index.html
In this url, phpmd PHP/Depend/DbusUI xml codesize --reportfile phpmd.xml --suffixes .php  do not work.
but --suffixes=.php   works well.

please fix it , 3ks

**Comment by ravage84** [comment]
You probably mean http://phpmd.org/documentation/index.html
Also it is mentioned in some other places.

Not sure what version you are using, but in 2.3.1 ``--suffixes php`` for a single extension and ``--suffixes php,phtml`` for multiple extensions work for me.

``--suffixes=.php`` works because the CLI ignores the parameter ``--suffixes=`` completly because it is not a valid parameter.

**Comment by jorissteyn** [comment]
I believe the README should be updated as well:

-    phpmd PHP/Depend/DbusUI xml codesize --reportfile phpmd.xml --suffixes .php
+    phpmd PHP/Depend/DbusUI xml codesize --reportfile phpmd.xml --suffixes php

The current version is confusing because '--suffixes .ext' doesn't work, the listed file extensions should not have a leading dot.

**Comment by ravage84** [comment]
@jorissteyn feel free to update the README (and other places you find) and create a PR
I'd be happy to merge.
