### ISSUE TITLE
Option to cache results in between the runs

### ISSUE THREAD

**Issue by hakamairi** [phpmd/phpmd#534]
Similar to phpcs --cache, would it be possible, and if so is it planed to give user an option to cache the phpmd results in order to improve performance of consecutive executions?

**Comment by leandromacedo** [comment]
Any news regarding this? This would be really useful!

**Comment by tvbeek** [comment]
There is currently not any active plan to implement this. But feel free to create a PR for this function.

**Comment by mlavrinenko** [comment]
Can using  `pdepend.xml` be considered as a workaround?

```
<?xml version="1.0"?>
<symfony:container xmlns:symfony="http://symfony.com/schema/dic/services"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://pdepend.org/schema/dic/pdepend"
    xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">
    <config>
        <cache>
            <driver>memory</driver>
        </cache>
    </config>
</symfony:container>
```

I've just created the file and it gave me x2 of execution speed.
ps. The file driver is available too, but almost as slow as regular execution (though I'm using ssd)

**Comment by mhnaufal** [comment]
> Can using `pdepend.xml` be considered as a workaround?
> 
> ```
> <?xml version="1.0"?>
> <symfony:container xmlns:symfony="http://symfony.com/schema/dic/services"
>     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>     xmlns="http://pdepend.org/schema/dic/pdepend"
>     xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">
>     <config>
>         <cache>
>             <driver>memory</driver>
>         </cache>
>     </config>
> </symfony:container>
> ```
> 
> I've just created the file and it gave me x2 of execution speed. ps. The file driver is available too, but almost as slow as regular execution (though I'm using ssd)

But here in the PHPDepend docs (https://github.com/pdepend/pdepend/blob/2.13.0/src/site/rst/documentation/handbook/configuration/index.rst#cache) said that the use of **memory** driver "will force to parse the source on every call", it means there is no cache in there. Am I right, or anything I miss about on the docs?

**Comment by AJenbo** [comment]
it creates a runtime cache which will prevent repeat calculations during a single run

**Comment by frankdekker** [comment]
Is this still open for implementation? I _might_ be interested in adding a result caching feature.

**Flags:**
`--cache` or `--cache=.phpmd.cache.php`. will default to `.phpmd.cache.php` if `--cache` is used

**Store:**
- sha hash of the phpmd config
- sha hash of the cli arguments
- php version (necessary?)
- all files that were inspected with sha hash of the contents of that file.
- all issues that were found during inspection for that file
- ... anything else?

**Usage**
- compare the phpmd config + cli hashes are equal
- compare the php version is equal
- for each file compare the file content hash. If equal report the issues from the cache instead of running the inspection.
- After completion persist the cache results back to `.phpmd.cache.php` or the file specified by `--cache=<file>`


**Nice to have**
- cli toggle to do file modified timestamp compare instead of sha hash of the contents?

**Comment by AJenbo** [comment]
That would be fantastic!

PHP version is probably best to have in there as there are feature levels that won't be analyzed if not supported. Though it probably can't analyze a file that uses unsupported features.
You should probably also make a check on the installed version of PHPMD and it's dependencies.

**Comment by frankdekker** [comment]
> That would be fantastic!
> 
> PHP version is probably best to have in there as there are feature levels that won't be analyzed if not supported. Though it probably can't analyze a file that uses unsupported features. You should probably also make a check on the installed version of PHPMD and it's dependencies.

Updated the above comment. made phpversion mandatory, added composer.lock

**Comment by ndench** [comment]
Sounds like a good plan @frankdekker!
