### ISSUE TITLE
UnusedFormalParamter is not aware of absolute func_get_args() when class is in namespace

### ISSUE THREAD

**Issue by vertexvaar** [phpmd/phpmd#574]
The function `func_get_args()` in a method uses all defined and undefined parameters of a method. (Same goes for positional arguments when using `func_get_arg(<index>)`). When the class of the method is in a namespace phpmd does recognize `\func_get_args()` but not `func_get_args()` which is the same if there is no function defined in the same namespace.

**Comment by kylekatarnls** [comment]
Hello, `<index>` can be a dynamic value in your example such as `mt_rand(0, 3)` or any external value on which we can't know which parameter it will refer to. So a muter should be used in your PHPDoc of the function:
```
@SuppressWarnings(PHPMD.UnusedFormalParamter) $fooBar is used via func_get_arg(3)
```
And only if you're absolutely sure there is no better way to code your function (a more explicit way which would help the next developer to know what the argument is intended to be and would not fail in PHPMD).

My position is: If PHPMD couldn't detect the usage of the parameter because it's hidden behind a `func_get_arg`, a dynamic variable or some opaque magic stuff, then other developers including the future your may also be confused by this way to do. So it's actually also a mess PHPMD is not wrong to point as a possible piece of code that can be improved.
