### ISSUE TITLE
Support for PHP readonly class feature

### ISSUE THREAD

**Issue by bladl** [phpmd/phpmd#998]
- PHPMD version: 2.13.0
- PHP Version: 8.2
- Installation type: (composer)

### Current Behavior
Unexpected token: readonly, line: 26, col: 7, file: ...

### Expected Behavior
Classes defined in format `final readonly class PhoneNumber` are valid in php 8.2

### Steps To Reproduce:
Define any `readonly` class and run mess detector

**Comment by tvbeek** [comment]
@bladl can you do a small thing and verify that is a problem without the final? I suspect the error is from PDepend and it fixed with: https://github.com/pdepend/pdepend/pull/642 (that doesn't yet have a release.)

If possible you can use the latest version by require pdepend/pdepend:dev-master as composer dependency.

**Comment by bladl** [comment]
@tvbeek yes, seems like everything works just fine with  `"pdepend/pdepend": "dev-master",`

**Comment by tvbeek** [comment]
@bladl thanks for the fast feedback 😃 👍
